version: '2'
services:
  connector-app:
    image: connector
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://connector-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=connector
      - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    ports:
      - 8085:8085
  connector-mongodb:
    extends:
      file: mongodb.yml
      service: connector-mongodb
